name: Sync Fork

on:
  schedule:
    # Run the workflow every day at midnight (adjust as needed)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering of the workflow
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          repository: davidwuest/wp-disable-emails
          ref: main

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/webaware/disable-emails.git
          git fetch upstream

      - name: Sync with Upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
